#pragma once

/**
 * @file    adam-sdk.hpp
 * @author  dexus1337
 * @brief   Umbrella header for the ADAM SDK, including all necessary headers for using the SDK in external applications and modules.
 * @version 1.0
 * @date    25.04.2026
 */

#include "api/api-sdk.hpp"
#include "configuration/configuration-item.hpp"
#include "configuration/parameters/configuration-parameter.hpp"
#include "configuration/parameters/configuration-parameter-list.hpp"
#include "configuration/parameters/configuration-parameter-list-sorted.hpp"
#include "configuration/parameters/configuration-parameter-boolean.hpp"
#include "configuration/parameters/configuration-parameter-double.hpp"
#include "configuration/parameters/configuration-parameter-integer.hpp"
#include "configuration/parameters/configuration-parameter-string.hpp"
#include "configuration/parameters/configuration-parameter-reference.hpp"
#include "controller/controller.hpp"
#include "controller/registry.hpp"
#include "controller/registry-module-manager.hpp"
#include "controller/controller-cmd-dispatcher.hpp"
#include "commander/messages/type.hpp"
#include "commander/messages/command.hpp"
#include "commander/messages/response.hpp"
#include "commander/messages/event.hpp"
#include "commander/messages/message-structs.hpp"
#include "commander/messages/message-serializer.hpp"
#include "commander/commander-event-dispatcher.hpp"
#include "commander/registry-view.hpp"
#include "commander/module-view.hpp"
#include "commander/commander.hpp"
#include "data/format.hpp"
#include "data/parser.hpp"
#include "data/encoder.hpp"
#include "data/processor.hpp"
#include "data/processors/filter.hpp"
#include "data/processors/converter.hpp"
#include "data/port.hpp"
#include "data/port-types/port-input.hpp"
#include "data/port-types/port-output.hpp"
#include "data/port-types/port-in-out.hpp"
#include "data/port-types/port-internal.hpp"
#include "data/connection.hpp"
#include "data/inspector.hpp"
#include "memory/memory.hpp"
#include "memory/memory-signaled.hpp"
#include "memory/buffer/buffer.hpp"
#include "memory/buffer/buffer-manager.hpp"
#include "module/module.hpp"
#include "module/module-internal.hpp"
#include "factory/factory.hpp"
#include "hash/rapidhash.h"
#include "hash/rapidhash-ct.h"
#include "types/string-hashed.hpp"
#include "types/string-hashed-ct.hpp"
#include "types/queue-shared.hpp"
#include "types/queue-shared-duplex.hpp"
#include "types/vector-double-buffer.hpp"
#include "version/version.hpp"
#include "logger/log.hpp"
#include "logger/logger.hpp"
#include "logger/logger-sink.hpp"
#include "os/os.hpp"
#include "resources/language.hpp"
#include "resources/language-strings.hpp"