/**
 * @file    gui-strings.cpp
 * @author  dexus1337
 * @brief   Implements string translation lookup table for the GUI
 * @version 1.0
 * @date    13.06.2026
 */

#include "gui-strings.hpp"

#include <unordered_map>
#include <array>

namespace adam::gui 
{
    const char* get_gui_string(gui_string_id id, adam::language lang)
    {
        static const std::unordered_map<gui_string_id, std::array<const char*, adam::languages_count>> translations =
        {
            { gui_string_id::main_ui,                     { "Main UI###MainUI", "Hauptbenutzeroberfläche###MainUI" } },
            { gui_string_id::menu_view,                   { "View", "Ansicht" } },
            { gui_string_id::menu_show_log,               { "Show Log", "Protokoll anzeigen" } },
            { gui_string_id::menu_show_performance,       { "Show Performance Overlay", "Leistungsübersicht anzeigen" } },
            { gui_string_id::menu_settings,               { "Settings", "Einstellungen" } },
            { gui_string_id::menu_gui_mode,               { "GUI Mode", "GUI-Modus" } },
            { gui_string_id::gui_mode_default,            { "Default", "Standard" } },
            { gui_string_id::gui_mode_immediate,          { "Immediate", "Unmittelbar" } },
            { gui_string_id::menu_fps_limit,              { "FPS Limit", "FPS-Limit" } },
            { gui_string_id::fps_10,                      { "10 FPS", "10 FPS" } },
            { gui_string_id::fps_30,                      { "30 FPS", "30 FPS" } },
            { gui_string_id::fps_60,                      { "60 FPS", "60 FPS" } },
            { gui_string_id::fps_120,                     { "120 FPS", "120 FPS" } },
            { gui_string_id::fps_vsync,                   { "VSync", "VSync" } },
            { gui_string_id::fps_unlimited,               { "Unlimited", "Unbegrenzt" } },
            { gui_string_id::combo_language,              { "Language###Lang", "Sprache###Lang" } },
            { gui_string_id::slider_font_scale,           { "Font Scale###FontScale", "Schriftskalierung###FontScale" } },
            { gui_string_id::combo_theme,                 { "Theme###Theme", "Design###Theme" } },
            { gui_string_id::theme_dark,                  { "Dark", "Dunkel" } },
            { gui_string_id::theme_light,                 { "Light", "Hell" } },
            { gui_string_id::btn_clear_log,               { "Clear Log###ClearLog", "Protokoll leeren###ClearLog" } },
            { gui_string_id::lbl_commander_connected,     { "Connected to ADAM", "Verbunden mit ADAM" } },
            { gui_string_id::lbl_commander_disconnected,  { "Disconnected from ADAM", "Nicht verbunden mit ADAM" } },
            { gui_string_id::lbl_log_console,             { "Log Console", "Protokollkonsole" } },
            { gui_string_id::combo_log_level_options,     { "Trace\0Info\0Warning\0Error\0\0", "Trace\0Info\0Warnung\0Fehler\0\0" } },
            { gui_string_id::tbl_time,                    { "Time", "Zeit" } },
            { gui_string_id::tbl_level,                   { "Level", "Ebene" } },
            { gui_string_id::tbl_message,                 { "Message", "Nachricht" } },
            { gui_string_id::lbl_performance_overlay,     { "Performance Overlay###PerfOverlay", "Leistungsübersicht###PerfOverlay" } },
            { gui_string_id::lbl_fps,                     { "FPS: %.1f (%.3f ms/frame)", "FPS: %.1f (%.3f ms/Frame)" } },
            { gui_string_id::lbl_cpu,                     { "CPU: %.1f%%", "CPU: %.1f%%" } },
            { gui_string_id::lbl_ram,                     { "RAM: %.1f/%.1f GB (%.0f%%)", "RAM: %.1f/%.1f GB (%.0f%%)" } },
            { gui_string_id::menu_overlay_custom,         { "Custom", "Benutzerdefiniert" } },
            { gui_string_id::menu_overlay_top_left,       { "Top-left", "Oben links" } },
            { gui_string_id::menu_overlay_top_right,      { "Top-right", "Oben rechts" } },
            { gui_string_id::menu_overlay_bottom_left,    { "Bottom-left", "Unten links" } },
            { gui_string_id::menu_overlay_bottom_right,   { "Bottom-right", "Unten rechts" } },
            { gui_string_id::menu_overlay_position,       { "Position", "Position" } },
            { gui_string_id::menu_overlay_content,        { "Content", "Inhalt" } },
            { gui_string_id::menu_overlay_show_fps,       { "Frames per Second (FPS)", "Bilder pro Sekunde (FPS)" } },
            { gui_string_id::menu_overlay_show_cpu,       { "Processor (CPU) Usage", "Prozessor (CPU) Auslastung" } },
            { gui_string_id::menu_overlay_show_ram,       { "Memory (RAM) Usage", "Arbeitsspeicher (RAM) Auslastung" } },
            { gui_string_id::tab_management,              { "Management###TabManagement", "Verwaltung###TabManagement" } },
            { gui_string_id::tab_modules,                 { "Modules###TabModules", "Module###TabModules" } },
            { gui_string_id::tab_information,             { "About###TabInformation", "Über###TabInformation" } },
            { gui_string_id::tab_configuration,           { "Configuration###TabConfiguration", "Konfiguration###TabConfiguration" } },
            { gui_string_id::tbl_load,                    { "Load", "Laden" } },
            { gui_string_id::tbl_name,                    { "Name", "Name" } },
            { gui_string_id::tbl_status,                  { "Status", "Status" } },
            { gui_string_id::tbl_version,                 { "Version", "Version" } },
            { gui_string_id::tbl_path,                    { "Path", "Pfad" } },
            { gui_string_id::stat_available,              { "Available", "Verfügbar" } },
            { gui_string_id::stat_loaded,                 { "Loaded", "Geladen" } },
            { gui_string_id::stat_unavailable,            { "Unavailable", "Nicht verfügbar" } },
            { gui_string_id::tt_incompat_sdk,             { "Requires newer SDK version", "Benötigt neuere SDK-Version" } },
            { gui_string_id::tt_incompat_unknown,         { "Unknown incompatibility reason", "Unbekannter Inkompatibilitätsgrund" } },
            { gui_string_id::lbl_module_paths,            { "Module Paths", "Modulpfade" } },
            { gui_string_id::btn_add_path,                { "Add", "Hinzufügen" } },
            { gui_string_id::btn_remove_path,             { "Remove", "Entfernen" } },
            { gui_string_id::btn_scan_modules,            { "Scan for Modules", "Nach Modulen suchen" } },
            { gui_string_id::ph_new_path,                 { "Enter new path...", "Neuen Pfad eingeben..." } },
            { gui_string_id::lbl_modules,                 { "Modules", "Module" } },
            { gui_string_id::tbl_index,                   { "#", "#" } },
            { gui_string_id::btn_create_connection,       { "Create Connection", "Verbindung erstellen" } },
            { gui_string_id::btn_create_port,             { "Create Port", "Port erstellen" } },
            { gui_string_id::lbl_inputs,                  { "Inputs", "Eingänge" } },
            { gui_string_id::lbl_outputs,                 { "Outputs", "Ausgänge" } },
            { gui_string_id::lbl_processors,              { "Processors", "Prozessoren" } },
            { gui_string_id::dlg_create_connection,       { "Create New Connection", "Neue Verbindung erstellen" } },
            { gui_string_id::dlg_create_port,             { "Create New Port", "Neuen Port erstellen" } },
            { gui_string_id::btn_cancel,                  { "Cancel", "Abbrechen" } },
            { gui_string_id::btn_remove,                  { "Remove", "Entfernen" } },
            { gui_string_id::btn_create,                  { "Create", "Erstellen" } },
            { gui_string_id::lbl_port_type,               { "Port Type", "Port-Typ" } },
            { gui_string_id::btn_start,                   { "Start", "Starten" } },
            { gui_string_id::btn_stop,                    { "Stop", "Stoppen" } },
            { gui_string_id::btn_add_input,               { "Add Input", "Eingang hinzufügen" } },
            { gui_string_id::btn_add_output,              { "Add Output", "Ausgang hinzufügen" } },
            { gui_string_id::btn_add_processor,           { "Add Processor", "Prozessor hinzufügen" } },
            { gui_string_id::lbl_connection,              { "Connection Name", "Name der Verbindung" } },
            { gui_string_id::btn_delete,                  { "Delete", "Löschen" } },
            { gui_string_id::dlg_delete_connection,       { "Delete Connection", "Verbindung löschen" } },
            { gui_string_id::msg_delete_connection_confirm, { "Are you sure you want to delete this connection?\nThis action cannot be undone.", "Möchten Sie diese Verbindung wirklich löschen?\nDiese Aktion kann nicht rückgängig gemacht werden." } },
            { gui_string_id::dlg_delete_port,             { "Delete Port", "Port löschen" } },
            { gui_string_id::msg_delete_port_confirm,     { "This port is not used in any other connection.\n\nWhat would you like to do?\n - Delete Port: Completely destroys the port and removes it from the system.\n - Remove Port: Removes it from this connection, but keeps it available for future use.", "Dieser Port wird in keiner anderen Verbindung verwendet.\n\nWas möchten Sie tun?\n - Port Löschen: Zerstört den Port vollständig und entfernt ihn aus dem System.\n - Port Entfernen: Entfernt ihn aus dieser Verbindung, behält ihn aber für spätere Verwendung." } },
            { gui_string_id::btn_ok,                      { "OK", "OK" } },
            { gui_string_id::lbl_no_description,          { "No description available.", "Keine Beschreibung verfügbar." } },
            { gui_string_id::lbl_available_ports,         { "Available Ports", "Verfügbare Ports" } },
            { gui_string_id::lbl_available_data_formats,  { "Available Data Formats", "Verfügbare Datenformate" } },
            { gui_string_id::lbl_available_processors,    { "Available Processors", "Verfügbare Prozessoren" } },
            { gui_string_id::lbl_port_direction,          { "Direction", "Richtung" } },
            { gui_string_id::lbl_badge_input,             { "Input", "Eingang" } },
            { gui_string_id::lbl_badge_output,            { "Output", "Ausgang" } },
            { gui_string_id::lbl_badge_in_short,          { "In", "Ein" } },
            { gui_string_id::lbl_badge_out_short,         { "Out", "Aus" } },
            { gui_string_id::lbl_processor_type,          { "Type", "Typ" } },
            { gui_string_id::lbl_filter,                  { "Filter", "Filter" } },
            { gui_string_id::lbl_converter,               { "Converter", "Konverter" } },
            { gui_string_id::lbl_existing_ports,          { "Existing Ports", "Existierende Ports" } },
            { gui_string_id::lbl_new_ports,               { "Create new Port", "Neuen Port erstellen" } },
            { gui_string_id::lbl_existing_filters,        { "Existing Filters", "Existierende Filter" } },
            { gui_string_id::lbl_new_filters,             { "Create new Filter", "Neuen Filter erstellen" } },
            { gui_string_id::lbl_existing_converters,     { "Existing Converters", "Existierende Konverter" } },
            { gui_string_id::lbl_new_converters,          { "Create new Converter", "Neuen Konverter erstellen" } },
            { gui_string_id::tt_module_missing,           { "Module '%s' is missing or not loaded.", "Modul '%s' fehlt oder ist nicht geladen." } },
            { gui_string_id::lbl_sort_by,                 { "Sort by:", "Sortieren nach:" } },
            { gui_string_id::sort_name_asc,               { "Name (Ascending)", "Name (aufsteigend)" } },
            { gui_string_id::sort_name_desc,              { "Name (Descending)", "Name (absteigend)" } },
            { gui_string_id::sort_date_asc,               { "Created (Old -> New)", "Erstellt (Alt -> Neu)" } },
            { gui_string_id::sort_date_desc,              { "Created (New -> Old)", "Erstellt (Neu -> Alt)" } },
            { gui_string_id::sort_edited_asc,             { "Edited (Old -> New)", "Bearbeitet (Alt -> Neu)" } },
            { gui_string_id::sort_edited_desc,            { "Edited (New -> Old)", "Bearbeitet (Neu -> Alt)" } },
            { gui_string_id::sort_custom,                 { "Custom", "Benutzerdefiniert" } },
            { gui_string_id::lbl_move_connection,         { "Move %s", "%s verschieben" } },
            { gui_string_id::dlg_add_input_port_to,       { "Add Input Port to %s###PortPopup", "Eingangsport zu %s hinzufügen###PortPopup" } },
            { gui_string_id::dlg_add_output_port_to,      { "Add Output Port to %s###PortPopup", "Ausgangsport zu %s hinzufügen###PortPopup" } },
            { gui_string_id::dlg_add_port,                { "Add Port###PortPopup", "Port hinzufügen###PortPopup" } },
            { gui_string_id::lbl_inject_data,             { "Inject Data", "Daten injizieren" } },
            { gui_string_id::btn_inject,                  { "Inject", "Injizieren" } },
            { gui_string_id::lbl_stat_handled,            { "Handled: %llu msgs (%s)", "Verarbeitet: %llu Nachr. (%s)" } },
            { gui_string_id::lbl_stat_discarded,          { "Discarded: %llu msgs (%s)", "Verworfen: %llu Nachr. (%s)" } },
            { gui_string_id::lbl_stat_unavailable,        { "Statistics unavailable", "Statistiken nicht verfügbar" } },
            { gui_string_id::btn_remove_port,             { "Remove Port", "Port entfernen" } },
            { gui_string_id::btn_remove_processor,        { "Remove Processor", "Prozessor entfernen" } },
            { gui_string_id::lbl_data_inspector,          { "Data Inspector", "Dateninspektor" } },
            { gui_string_id::lbl_active_inspectors,       { "Active Inspectors", "Aktive Inspektoren" } },
            { gui_string_id::lbl_inspect,                 { "Inspect", "Inspizieren" } },
            { gui_string_id::col_inspect,                 { "On", "An" } },
            { gui_string_id::col_port_name,               { "Port Name", "Name des Ports" } },
            { gui_string_id::col_messages,                { "Messages", "Nachrichten" } },
            { gui_string_id::col_size,                    { "Size", "Größe" } },
            { gui_string_id::col_last_received,           { "Last Received", "Zuletzt empfangen" } },
            { gui_string_id::lbl_no_data,                 { "No data", "Keine Daten" } },
            { gui_string_id::btn_clear_data,              { "Clear Data", "Daten löschen" } },
            { gui_string_id::btn_clear_all_data,          { "Clear All Buffered Data", "Alle gepufferten Daten löschen" } },
            { gui_string_id::btn_clear_data_for,          { "Clear Data for \"%s\"", "Daten löschen für \"%s\"" } },
            { gui_string_id::col_index,                   { "Index", "Index" } },
            { gui_string_id::col_timestamp,               { "Timestamp", "Zeitstempel" } },
            { gui_string_id::col_preview_hex,             { "Preview (Hex)", "Vorschau (Hex)" } },
            { gui_string_id::col_preview_ascii,           { "Preview (ASCII)", "Vorschau (ASCII)" } },
            { gui_string_id::col_type,                    { "Type", "Typ" } },
            { gui_string_id::lbl_data_format,             { "Data Format", "Datenformat" } },
            { gui_string_id::lbl_input_port,              { "Input Port", "Eingangsport" } },
            { gui_string_id::lbl_output_port,             { "Output Port", "Ausgangsport" } },
            { gui_string_id::lbl_inout_port,              { "InOut Port", "Ein-/Ausgangsport" } },
            { gui_string_id::lbl_data_format_transparent_none, { "transparent (none)", "transparent (keines)" } },
            { gui_string_id::lbl_received,                { "Received", "Empfangen" } },
            { gui_string_id::lbl_forwarded,               { "Forwarded", "Weitergeleitet" } },
            { gui_string_id::lbl_discarded,               { "Discarded", "Verworfen" } },
            { gui_string_id::lbl_statistics,              { "Statistics", "Statistiken" } },
            { gui_string_id::btn_copy_hex,                { "Copy Hex", "Hex kopieren" } },
            { gui_string_id::btn_copy_ascii,              { "Copy ASCII", "ASCII kopieren" } },
            { gui_string_id::btn_copy_hex_dump,           { "Copy Hex Dump", "Hex-Dump kopieren" } },
            { gui_string_id::btn_copy_message,            { "Copy Message", "Nachricht kopieren" } },
            { gui_string_id::btn_copy_row,                { "Copy Row", "Zeile kopieren" } },
            { gui_string_id::lbl_replay_file,             { "File", "Datei" } },
            { gui_string_id::lbl_replay_instant,          { "instant", "sofort" } },
            { gui_string_id::lbl_parameters,              { "Parameters###Parameters", "Parameter###Parameters" } },
            { gui_string_id::col_config_name,             { "Configuration Name", "Konfigurationsname" } },
            { gui_string_id::col_filename,                { "Filename", "Dateiname" } },
            { gui_string_id::col_description,             { "Description", "Beschreibung" } },
            { gui_string_id::col_created,                 { "Created", "Erstellt" } },
            { gui_string_id::col_modified,                { "Modified", "Geändert" } },
            { gui_string_id::col_counts,                  { "Ports / Processors / Connections", "Ports / Prozessoren / Verbindungen" } },
            { gui_string_id::btn_scan_configs,            { "Scan Configs", "Configs Scannen" } },
            { gui_string_id::btn_load_config,             { "Import", "Importieren" } },
            { gui_string_id::btn_export_config,           { "Export", "Exportieren" } },
            { gui_string_id::btn_delete_config,           { "Delete", "Löschen" } },
            { gui_string_id::dlg_delete_config_confirm,   { "Are you sure you want to delete this configuration?", "Sind Sie sicher, dass Sie diese Konfiguration löschen möchten?" } },
            { gui_string_id::dlg_save_config,             { "Export Configuration", "Konfiguration exportieren" } },
            { gui_string_id::lbl_config_name,             { "Name", "Name" } },
            { gui_string_id::lbl_config_description,      { "Description", "Beschreibung" } },
            { gui_string_id::lbl_configuration_paths,     { "Configuration Paths", "Konfigurationspfade" } },
            { gui_string_id::lbl_available_configurations,{ "Available Configurations", "Verfügbare Konfigurationen" } },
            { gui_string_id::lbl_config_settings,         { "Configuration Settings", "Konfigurationseinstellungen" } },
            { gui_string_id::btn_export,                  { "Export", "Exportieren" } },
            { gui_string_id::btn_save,                    { "Save", "Speichern" } },
            { gui_string_id::msg_about_description,       { "Advanced Data Analysis and Management (ADAM) is a modular, high-performance platform for routing, analyzing, and processing real-time data streams.", "Advanced Data Analysis and Management (ADAM) ist eine modulare Hochleistungsplattform für das Routing, die Analyse und die Verarbeitung von Echtzeit-Datenströmen." } },
            { gui_string_id::msg_about_copyright1,        { "Copyright (c) 2026 dexus1337.", "Copyright (c) 2026 dexus1337." } },
            { gui_string_id::msg_about_copyright2,        { "All rights reserved.", "Alle Rechte vorbehalten." } }
        };

        auto it = translations.find(id);
        if (it != translations.end())
            return it->second[lang];

        return language_strings::unknown_type_message("gui_string_id", id, lang).data();
    }
}
