#include "cli-strings.hpp"

#include <unordered_map>
#include <array>

namespace adam::cli
{
    const char* get_cli_string(cmd_string_id id, adam::language lang)
    {
        static const std::unordered_map<cmd_string_id, std::array<const char*, adam::languages_count>> translations =
        {
            { cmd_string_id::cannot_connect_controller,   { "Cannot connect to controller", "Verbindung zum Controller fehlgeschlagen" } },
            { cmd_string_id::connected_controller,        { "Connected to controller!", "Verbunden mit Controller!" } },
            { cmd_string_id::failed_connect_logger,       { "Failed to connect to the logger.", "Verbindung zum Logger fehlgeschlagen." } },
            { cmd_string_id::connected_logger,            { "Connected to logger!", "Verbunden mit Logger!" } },
            { cmd_string_id::failed_connect_logger_sink,  { "Failed to connect to the logger sink.", "Verbindung zum Logger Sink fehlgeschlagen." } },
            { cmd_string_id::connected_logger_sink,       { "Connected to logger sink!", "Verbunden mit Logger Sink!" } },
            { cmd_string_id::usage_setlang,               { "Usage: setlang <de|en>", "Verwendung: setlang <de|en>" } },
            { cmd_string_id::usage_loglvl,                { "Usage: loglvl <0|1|2|3> or <trace|info|warn|error>", "Verwendung: loglvl <0|1|2|3> oder <trace|info|warn|error>" } },
            { cmd_string_id::log_level_updated,           { "Log level updated.", "Protokollstufe aktualisiert." } },
            { cmd_string_id::failed_destroy_logger_sink,  { "Failed to destroy the logger sink.", "Logger Sink konnte nicht zerstört werden." } },
            { cmd_string_id::failed_destroy_logger,       { "Failed to destroy the logger.", "Logger konnte nicht zerstört werden." } },
            { cmd_string_id::failed_destroy_commander,    { "Failed to destroy the commander.", "Commander konnte nicht zerstört werden." } },
            { cmd_string_id::exiting,                     { "Exiting!", "Beenden!" } },
            { cmd_string_id::unknown_command,             { "Unknown command.", "Unbekannter Befehl." } },
            { cmd_string_id::available_commands,          { "Available commands:", "Verfügbare Befehle:" } },
            { cmd_string_id::desc_help,                   { "Lists all available commands and their descriptions", "Listet alle verfügbaren Befehle und deren Beschreibungen auf" } },
            { cmd_string_id::desc_setlang,                { "Changes the application language (de, en)", "Ändert die Anwendungssprache (de, en)" } },
            { cmd_string_id::desc_loglvl,                 { "Sets the logging level (0=trace, 1=info, 2=warn, 3=error)", "Legt die Protokollierungsstufe fest (0=trace, 1=info, 2=warn, 3=error)" } },
            { cmd_string_id::desc_mod_scan,               { "Scans for new modules in module paths", "Sucht nach neuen Modulen in den Modulpfaden" } },
            { cmd_string_id::desc_mod_load,               { "Loads a module by name", "Lädt ein Modul nach Namen" } },
            { cmd_string_id::usage_mod_load,              { "Usage: mod_load <name>", "Verwendung: mod_load <name>" } },
            { cmd_string_id::desc_mod_unload,             { "Unloads a module by name", "Entlädt ein Modul nach Namen" } },
            { cmd_string_id::usage_mod_unload,            { "Usage: mod_unload <name>", "Verwendung: mod_unload <name>" } },
            { cmd_string_id::desc_mod_list,               { "Lists all modules", "Listet alle Module auf" } },
            { cmd_string_id::desc_port_create,            { "Creates a new port", "Erstellt einen neuen Port" } },
            { cmd_string_id::usage_port_create,           { "Usage: port_create <module> <type> <name>", "Verwendung: port_create <module> <type> <name>" } },
            { cmd_string_id::desc_port_destroy,           { "Destroys a port by name", "Zerstört einen Port nach Namen" } },
            { cmd_string_id::usage_port_destroy,          { "Usage: port_destroy <name>", "Verwendung: port_destroy <name>" } },
            { cmd_string_id::desc_port_start,             { "Starts a port by name", "Startet einen Port nach Namen" } },
            { cmd_string_id::usage_port_start,            { "Usage: port_start <name>", "Verwendung: port_start <name>" } },
            { cmd_string_id::desc_port_stop,              { "Stops a port by name", "Stoppt einen Port nach Namen" } },
            { cmd_string_id::usage_port_stop,             { "Usage: port_stop <name>", "Verwendung: port_stop <name>" } },
            { cmd_string_id::desc_port_list,              { "Lists all ports", "Listet alle Ports auf" } },
            { cmd_string_id::desc_conn_create,            { "Creates a new connection", "Erstellt eine neue Verbindung" } },
            { cmd_string_id::usage_conn_create,           { "Usage: conn_create <name>", "Verwendung: conn_create <name>" } },
            { cmd_string_id::desc_conn_destroy,           { "Destroys a connection by name", "Zerstört eine Verbindung nach Namen" } },
            { cmd_string_id::usage_conn_destroy,          { "Usage: conn_destroy <name>", "Verwendung: conn_destroy <name>" } },
            { cmd_string_id::desc_conn_start,             { "Starts a connection by name", "Startet eine Verbindung nach Namen" } },
            { cmd_string_id::usage_conn_start,            { "Usage: conn_start <name>", "Verwendung: conn_start <name>" } },
            { cmd_string_id::desc_conn_stop,              { "Stops a connection by name", "Stoppt eine Verbindung nach Namen" } },
            { cmd_string_id::usage_conn_stop,             { "Usage: conn_stop <name>", "Verwendung: conn_stop <name>" } },
            { cmd_string_id::desc_conn_add_port,          { "Adds a port to a connection", "Fügt einen Port zu einer Verbindung hinzu" } },
            { cmd_string_id::usage_conn_add_port,         { "Usage: conn_add_port <conn_name> <port_name> <in|out>", "Verwendung: conn_add_port <conn_name> <port_name> <in|out>" } },
            { cmd_string_id::desc_conn_rm_port,           { "Removes a port from a connection", "Entfernt einen Port aus einer Verbindung" } },
            { cmd_string_id::usage_conn_rm_port,          { "Usage: conn_rm_port <conn_name> <port_name> <in|out>", "Verwendung: conn_rm_port <conn_name> <port_name> <in|out>" } },
            { cmd_string_id::desc_conn_list,              { "Lists all connections", "Listet alle Verbindungen auf" } },
            { cmd_string_id::desc_port_rename,            { "Renames a port", "Benennt einen Port um" } },
            { cmd_string_id::usage_port_rename,           { "Usage: port_rename <old_name> <new_name>", "Verwendung: port_rename <old_name> <new_name>" } },
            { cmd_string_id::desc_port_params,            { "Lists all parameters of a port", "Listet alle Parameter eines Ports auf" } },
            { cmd_string_id::usage_port_params,           { "Usage: port_params <port_name>", "Verwendung: port_params <port_name>" } },
            { cmd_string_id::desc_port_params_info,        { "Lists valid parameters and rules of a port", "Listet gültige Parameter und Regeln eines Ports auf" } },
            { cmd_string_id::usage_port_params_info,       { "Usage: port_params_info <port_name>", "Verwendung: port_params_info <port_name>" } },
            { cmd_string_id::desc_port_set_param,         { "Sets a parameter of a port", "Setzt einen Parameter eines Ports" } },
            { cmd_string_id::usage_port_set_param,        { "Usage: port_set_param <port_name> <param_name> <value>", "Verwendung: port_set_param <port_name> <param_name> <value>" } },
            { cmd_string_id::desc_port_inject,            { "Injects hex data into a port", "Injiziert Hex-Daten in einen Port" } },
            { cmd_string_id::usage_port_inject,           { "Usage: port_inject <port_name> <hex_data> <in|out>", "Verwendung: port_inject <port_name> <hex_data> <in|out>" } },
            { cmd_string_id::desc_port_inspect,           { "Inspects data arriving at a port", "Überprüft am Port ankommende Daten" } },
            { cmd_string_id::usage_port_inspect,          { "Usage: port_inspect <port_name>", "Verwendung: port_inspect <port_name>" } },
            { cmd_string_id::desc_conn_inspect,           { "Inspects data arriving at a connection", "Überprüft an einer Verbindung ankommende Daten" } },
            { cmd_string_id::usage_conn_inspect,          { "Usage: conn_inspect <conn_name> <in|out>", "Verwendung: conn_inspect <conn_name> <in|out>" } },
            { cmd_string_id::inspector_started,           { "Inspector started. Press 'Enter' to stop...", "Inspektor gestartet. Drücken Sie 'Enter' zum Stoppen..." } },
            { cmd_string_id::inspector_stopped,           { "Inspector stopped.", "Inspektor gestoppt." } },
            { cmd_string_id::desc_conn_rename,            { "Renames a connection", "Benennt eine Verbindung um" } },
            { cmd_string_id::usage_conn_rename,           { "Usage: conn_rename <old_name> <new_name>", "Verwendung: conn_rename <old_name> <new_name>" } },
            { cmd_string_id::desc_conn_set_fmt_in,        { "Sets the input format of a connection", "Setzt das Eingabeformat einer Verbindung" } },
            { cmd_string_id::usage_conn_set_fmt_in,       { "Usage: conn_set_fmt_in <conn_name> <format> [module]", "Verwendung: conn_set_fmt_in <conn_name> <format> [module]" } },
            { cmd_string_id::desc_conn_set_fmt_out,       { "Sets the output format of a connection", "Setzt das Ausgabeformat einer Verbindung" } },
            { cmd_string_id::usage_conn_set_fmt_out,      { "Usage: conn_set_fmt_out <conn_name> <format> [module]", "Verwendung: conn_set_fmt_out <conn_name> <format> [module]" } },
            { cmd_string_id::desc_mod_path_add,           { "Adds a module search path", "Fügt einen Modul-Suchpfad hinzu" } },
            { cmd_string_id::usage_mod_path_add,          { "Usage: mod_path_add <path>", "Verwendung: mod_path_add <path>" } },
            { cmd_string_id::desc_mod_path_rm,            { "Removes a module search path by index", "Entfernt einen Modul-Suchpfad nach Index" } },
            { cmd_string_id::usage_mod_path_rm,           { "Usage: mod_path_rm <index>", "Verwendung: mod_path_rm <index>" } },
            { cmd_string_id::err_param_invalid,           { "Invalid parameter value or out of range.", "Ungültiger Parameterwert oder außerhalb des Bereichs." } },
            { cmd_string_id::err_param_not_found,         { "Parameter not found.", "Parameter nicht gefunden." } },
            { cmd_string_id::desc_clean,                  { "Clears the terminal screen", "Leert den Terminalbildschirm" } },
            { cmd_string_id::desc_clear,                  { "Clears the terminal screen", "Leert den Terminalbildschirm" } },
            { cmd_string_id::desc_exit,                   { "Exits the application cleanly", "Beendet die Anwendung sauber" } },
            { cmd_string_id::desc_quit,                   { "Exits the application cleanly", "Beendet die Anwendung sauber" } },
            { cmd_string_id::desc_proc_create,            { "Creates a new processor", "Erstellt einen neuen Prozessor" } },
            { cmd_string_id::usage_proc_create,           { "Usage: proc_create <name> <type> [module] [filter|converter]", "Verwendung: proc_create <name> <type> [module] [filter|converter]" } },
            { cmd_string_id::desc_proc_destroy,           { "Destroys a processor by name", "Zerstört einen Prozessor nach Namen" } },
            { cmd_string_id::usage_proc_destroy,          { "Usage: proc_destroy <name>", "Verwendung: proc_destroy <name>" } },
            { cmd_string_id::desc_proc_rename,            { "Renames a processor", "Benennt einen Prozessor um" } },
            { cmd_string_id::usage_proc_rename,           { "Usage: proc_rename <old_name> <new_name>", "Verwendung: proc_rename <old_name> <new_name>" } },
            { cmd_string_id::desc_proc_params,            { "Lists all parameters of a processor", "Listet alle Parameter eines Prozessors auf" } },
            { cmd_string_id::usage_proc_params,           { "Usage: proc_params <processor_name>", "Verwendung: proc_params <processor_name>" } },
            { cmd_string_id::desc_proc_set_param,         { "Sets a parameter of a processor", "Setzt einen Parameter eines Prozessors" } },
            { cmd_string_id::usage_proc_set_param,        { "Usage: proc_set_param <processor_name> <param_name> <value>", "Verwendung: proc_set_param <processor_name> <param_name> <value>" } },
            { cmd_string_id::desc_proc_list,              { "Lists all processors", "Listet alle Prozessoren auf" } },
            { cmd_string_id::desc_conn_add_proc,          { "Adds a processor to a connection", "Fügt einen Prozessor zu einer Verbindung hinzu" } },
            { cmd_string_id::usage_conn_add_proc,         { "Usage: conn_add_proc <conn_name> <proc_name>", "Verwendung: conn_add_proc <conn_name> <proc_name>" } },
            { cmd_string_id::desc_conn_rm_proc,           { "Removes a processor from a connection", "Entfernt einen Prozessor aus einer Verbindung" } },
            { cmd_string_id::usage_conn_rm_proc,          { "Usage: conn_rm_proc <conn_name> <proc_name>", "Verwendung: conn_rm_proc <conn_name> <proc_name>" } },
            { cmd_string_id::desc_conn_reorder_proc,      { "Reorders a processor in a connection", "Ändert die Reihenfolge eines Prozessors in einer Verbindung" } },
            { cmd_string_id::usage_conn_reorder_proc,     { "Usage: conn_reorder_proc <conn_name> <proc_name> <new_index>", "Verwendung: conn_reorder_proc <conn_name> <proc_name> <new_index>" } },
            { cmd_string_id::desc_cfg_list,               { "Lists all configurations", "Listet alle Konfigurationen auf" } },
            { cmd_string_id::desc_cfg_scan,               { "Scans for configurations", "Sucht nach Konfigurationen" } },
            { cmd_string_id::desc_cfg_save,               { "Saves current state as a new configuration", "Speichert den aktuellen Zustand als neue Konfiguration" } },
            { cmd_string_id::usage_cfg_save,              { "Usage: cfg_save <name> [description]", "Verwendung: cfg_save <name> [description]" } },
            { cmd_string_id::desc_cfg_load,               { "Loads a configuration", "Lädt eine Konfiguration" } },
            { cmd_string_id::usage_cfg_load,              { "Usage: cfg_load <path_idx> <filename>", "Verwendung: cfg_load <path_idx> <filename>" } },
            { cmd_string_id::desc_cfg_export,             { "Exports current state to a configuration file", "Exportiert den aktuellen Zustand in eine Konfigurationsdatei" } },
            { cmd_string_id::usage_cfg_export,            { "Usage: cfg_export <path_idx> <filename> <name> [description]", "Verwendung: cfg_export <path_idx> <filename> <name> [description]" } },
            { cmd_string_id::desc_cfg_delete,             { "Deletes a configuration", "Löscht eine Konfiguration" } },
            { cmd_string_id::usage_cfg_delete,            { "Usage: cfg_delete <path_idx> <filename>", "Verwendung: cfg_delete <path_idx> <filename>" } },
            { cmd_string_id::desc_cfg_path_add,           { "Adds a config search path", "Fügt einen Konfigurations-Suchpfad hinzu" } },
            { cmd_string_id::usage_cfg_path_add,          { "Usage: cfg_path_add <path>", "Verwendung: cfg_path_add <path>" } },
            { cmd_string_id::desc_cfg_path_rm,            { "Removes a config search path by index", "Entfernt einen Konfigurations-Suchpfad nach Index" } },
            { cmd_string_id::usage_cfg_path_rm,           { "Usage: cfg_path_rm <index>", "Verwendung: cfg_path_rm <index>" } },
            { cmd_string_id::desc_cfg_path_list,          { "Lists config search paths", "Listet Konfigurations-Suchpfade auf" } },
            { cmd_string_id::desc_mod_path_list,          { "Lists module search paths", "Listet Modul-Suchpfade auf" } },
            { cmd_string_id::desc_cli_params_info,        { "Lists valid parameters and rules of the CLI", "Listet gültige Parameter und Regeln der CLI auf" } },
            { cmd_string_id::desc_cli_params,             { "Lists the current values of all CLI parameters", "Listet die aktuellen Werte aller CLI-Parameter auf" } },
            { cmd_string_id::desc_cli_set_param,          { "Sets a parameter of the CLI", "Setzt einen Parameter der CLI" } },
            { cmd_string_id::usage_cli_set_param,         { "Usage: cli_set_param <param_name> <value>", "Verwendung: cli_set_param <param_name> <value>" } }
        };

        auto it = translations.find(id);
        if (it != translations.end())
            return it->second[lang];
        
        return language_strings::unknown_type_message("cmd_string_id", static_cast<int>(id), lang).data();
    }
}